### ISSUE TITLE
Current TODO

### ISSUE THREAD

**Issue by burrrata** [burrrata/website#19]
- [x] put the Tic Tac Toe app in it's own file that can be imported as a component
- [x] merge `main-highlights.js` with `projects.js`
- [x] export PinnedProjectHighlights as a component to be displayed on the homepage
- [x] export ProjectHighlights to be it's own page `${siteURL}/projects`
- [x] link to the projects page via the homepage nav bar and a button in the ProjectHighlights section

**Comment by burrrata** [comment]
The TicTacToeApp and LatestAPOD components both need to be stateful. Currently I haven't figured out how to do this without breaking Docusaurus though... TODO!
